### ISSUE TITLE
Connect button doesn't work on Microsoft Teams

### ISSUE THREAD

**Issue by bnookala** [mattdot/botauth#10]
Due to the lack of support of a `SigninCard`, clicking the button doesn't open a URL, as one would expect. The C# AuthBot had also noted this issue and makes use of a `ThumbnailCard`: https://github.com/MicrosoftDX/AuthBot/blob/master/AuthBot/Dialogs/AzureAuthDialog.cs with a button that has an associated `openUrl` action.

**Comment by mattdot** [comment]
I'm planning on changing this to ThubnailCard in the new Flows feature

**Comment by bnookala** [comment]
@mattdot I have a fix ready, if you're ok with taking a PR :)

**Comment by mattdot** [comment]
Sure
