### ISSUE TITLE
Asking for my situation

### ISSUE THREAD

**Issue by binhpht** [mattdot/botauth#25]
Hey  I have 2 questions want to ask 
Question 1:  If I want authenticate my system via OAuth2, when user fill there loginID and password, the system will generate token, so which the stragety passport in this case
Question 2 : Could we use this solution when user communicate the bot via Mobile because as I imagine, the popup will be opened on mobile browse and Its may be hard to return token.
Thanks.

**Comment by mattdot** [comment]
You can use the generic passport-oauth2 strategy https://github.com/jaredhanson/passport-oauth2

It does open to the browser but it's pretty easy to copy the code on mobile and go back on iOS/Android to the previous app
