### ISSUE TITLE
[question] oauth flow in bots that are not web-based

### ISSUE THREAD

**Issue by palmerabollo** [mattdot/botauth#4]
I wonder how the middleware works in bots that are not web-based (for example a Facebook or a Skype bot that wants to use oauth to authenticate the user).

**Comment by mattdot** [comment]
It works in a similar way.  It sends a link / card button which opens in a browser to do the authentication.  The user gets a code that they type into the chat to complete the authentication.

**Comment by palmerabollo** [comment]
Thanks for the answer.
