### ISSUE TITLE
Cant find C# NuGets

### ISSUE THREAD

**Issue by aviatoredb** [mattdot/botauth#45]
Searched for AuthBot & BotAuth, nothing, nada.

**Comment by EricDahlvang** [comment]
Hi @aviatoredb 

BotAuth can be found here: https://www.nuget.org/packages/BotAuth/

In Visual Studio, it is necessary to click the "Include prerelease" checkbox:

![image](https://user-images.githubusercontent.com/11055362/36871080-dcec07fa-1d55-11e8-89e2-0670137fab04.png)

**Comment by aviatoredb** [comment]
Derp! Of course. Thank you.
