### ISSUE TITLE
Using Bot Framework State Service?

### ISSUE THREAD

**Issue by muebele** [mattdot/botauth#56]
Is this project using the Bot Framework State Service? Looking at the code, it seems like the AuthDialog and CallbackController are using it to pass back and forth the authentication values. Since the State Service is now deprecated, won't that cause problem using this code in production?  Or am I mistaken?

**Comment by EricDahlvang** [comment]
They are not using the default state service, but using https://github.com/Microsoft/BotBuilder-Azure

**Comment by muebele** [comment]
Got it, thanks.
